-- ============================================
-- SEED DATA - Production Ready
-- ============================================
-- No demo data - all restaurants are created through onboarding
-- This file intentionally left empty for production use
-- ============================================
